# Generated by Django 5.0.2 on 2024-02-07 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('idTratamiento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'Tratamientos',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('idVeterinario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Veterinario',
                'verbose_name_plural': 'Veterinarios',
                'db_table': 'Veterinarios',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('foto', models.ImageField(upload_to='mascotas')),
                ('fkCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestion.cliente')),
                ('fkTratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestion.tratamiento')),
                ('fkVeterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppGestion.veterinario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'Mascotas',
            },
        ),
    ]
