# Generated by Django 5.0.2 on 2024-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='Medellin', max_length=50),
        ),
    ]
