# Generated by Django 5.0.2 on 2024-02-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0003_mascota_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
