# Generated by Django 5.0.2 on 2024-02-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0005_alter_mascota_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='fkTratamiento',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='fkVeterinario',
        ),
    ]
