# Generated by Django 5.0.2 on 2024-02-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0006_remove_mascota_fktratamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fkMascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myAppGestion.mascota'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fkVeterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myAppGestion.veterinario'),
        ),
    ]
