# Generated by Django 5.0.2 on 2024-02-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0008_tratamiento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
