# Generated by Django 5.0.2 on 2024-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0013_alter_cliente_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='idMascota',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='idTratamiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='idVeterinario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
