# Generated by Django 5.0.2 on 2024-02-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0016_mascotasadopciones_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasadopciones',
            name='especie',
            field=models.CharField(choices=[('P', 'Perro'), ('G', 'Gato')], default='P', max_length=1),
        ),
    ]
