# Generated by Django 5.0.2 on 2024-02-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0018_alter_mascotasadopciones_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotasadopciones',
            name='sexo',
            field=models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], default='Hembra', max_length=6),
        ),
    ]
