# Generated by Django 5.0.2 on 2024-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0019_alter_mascotasadopciones_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasadopciones',
            name='foto',
            field=models.ImageField(default='foto', upload_to='adopciones'),
        ),
    ]
