# Generated by Django 5.0.2 on 2024-02-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0020_mascotasadopciones_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default=123456789, max_length=50),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='cedula',
            field=models.CharField(default=123456789, max_length=50),
        ),
    ]
