# Generated by Django 5.0.2 on 2024-02-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppGestion', '0021_cliente_cedula_veterinario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='precio',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
